name: armThrow
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch::pytorch::*=*cuda12*
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip
  - pip:
      - pybullet
      - stable-baselines3
      - gymnasium
      - wandb
      - PyYAML
      - imageio
      - nomkl  # This prevents Intel MKL's libomp conflicts