name: armThrow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - pybullet
      - stable-baselines3
      - gymnasium
      - wandb
      - PyYAML
      - imageio
